sources:
  - name: CountriesAPI
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com/
additionalTypeDefs: |
  extend type Continent {
    testProperty: String!
  }
additionalResolvers:
  - ./src/mesh/additionalContinentResolver
